// Copyright 2025 Google LLC
// Fuzz target for TinyOBJLoader real number parsing
// Targets: tinyobj::sr_parseReal3 (0% coverage, complexity 548)
// Tests the 3D coordinate parsing specifically

#define TINYOBJLOADER_IMPLEMENTATION
#include "tiny_obj_loader.h"
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string>
#include <sstream>
#include <vector>

// Fuzz target specifically for 3D coordinate parsing
extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
    if (size < 3) return 0;
    
    // Create various OBJ vertex lines with different number formats
    std::stringstream obj_stream;
    
    // Ensure null-terminated input
    std::string input((const char*)data, size);
    
    // Write a valid OBJ header
    obj_stream << "# OBJ file generated by fuzzer\n";
    obj_stream << "o fuzz_object\n";
    
    // Generate vertex lines using the fuzz input
    // Split input into lines and use each as a vertex coordinate
    size_t pos = 0;
    int vertex_count = 0;
    
    while (pos < size && vertex_count < 1000) {
        // Find next whitespace or end
        size_t end = pos;
        while (end < size && input[end] != ' ' && input[end] != '\t' && 
               input[end] != '\n' && input[end] != '\r') {
            end++;
        }
        
        if (end > pos) {
            // Create a vertex line with "v x y z" format
            // Extract three values from the fuzz data
            float x = 0, y = 0, z = 0;
            
            // Interpret bytes as floats (unsafe but good for fuzzing)
            if (end - pos >= sizeof(float)) {
                memcpy(&x, input.data() + pos, sizeof(float));
                pos += sizeof(float);
            }
            if (end - pos >= sizeof(float)) {
                memcpy(&y, input.data() + pos, sizeof(float));
                pos += sizeof(float);
            }
            if (end - pos >= sizeof(float)) {
                memcpy(&z, input.data() + pos, sizeof(float));
                pos += sizeof(float);
            }
            
            // Write as formatted vertex line
            obj_stream << "v " << x << " " << y << " " << z << "\n";
            vertex_count++;
        }
        
        // Skip whitespace
        while (pos < size && (input[pos] == ' ' || input[pos] == '\t' || 
                              input[pos] == '\n' || input[pos] == '\r')) {
            pos++;
        }
    }
    
    // Add face definitions if we have vertices
    if (vertex_count >= 3) {
        obj_stream << "f 1 2 3\n";
        if (vertex_count >= 4) {
            obj_stream << "f 1 2 3 4\n";  // quad face
        }
    }
    
    // Parse the generated OBJ data
    tinyobj::attrib_t attrib;
    std::vector<tinyobj::shape_t> shapes;
    std::vector<tinyobj::material_t> materials;
    
    std::string warn;
    std::string err;
    
    std::string obj_data = obj_stream.str();
    std::istringstream parse_stream(obj_data);
    
    tinyobj::LoadObj(
        &attrib,
        &shapes,
        &materials,
        &warn,
        &err,
        &parse_stream,
        NULL,
        true,   // triangulate
        false   // default_vcols_fallback
    );
    
    // Also test with raw fuzz input as OBJ (to catch edge cases)
    std::istringstream raw_stream(input);
    tinyobj::attrib_t attrib2;
    std::vector<tinyobj::shape_t> shapes2;
    std::vector<tinyobj::material_t> materials2;
    std::string warn2;
    std::string err2;
    
    tinyobj::LoadObj(
        &attrib2,
        &shapes2,
        &materials2,
        &warn2,
        &err2,
        &raw_stream,
        NULL,
        false,  // don't triangulate
        true    // default_vcols_fallback
    );
    
    return 0;
}
