# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2.0.0rc14.dev44+g1808e6e.d20260224'
__version_tuple__ = version_tuple = (2, 0, 0, 'dev44', 'g1808e6e.d20260224')
